### ISSUE TITLE
Error With /Stats

### ISSUE THREAD

**Issue by Enderborn1235** [Kowagatte/Damocles#1]
The error is as follows:
"[20:44:01] [Server thread/WARN]: [SevenKings] Task #86 for SevenKings v3.8 generated an exception
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_112]
	at xyz.almia.accountsystem.AccountStatus.valueOf(AccountStatus.java:1) ~[?:?]
	at xyz.almia.accountsystem.Account.getStatus(Account.java:22) ~[?:?]
	at xyz.almia.accountsystem.Tasks$4.run(Tasks.java:214) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-f950f8e-655d840]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]"

Please Help,
 -Enderborn1235

**Comment by Kowagatte** [comment]
Should be patched in latest updates, was a problem when players who already joined the server would join after the plugin was installed making the plugin think they already had character files generated.

**Comment by Enderborn1235** [comment]
Ok thanks.
